config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                      root GET    /                                                                                        users#new
#             relationships POST   /relationships(.:format)                                                                 relationships#create
#              relationship DELETE /relationships/:id(.:format)                                                             relationships#destroy
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                 edit_user GET    /users/:id/edit(.:format)                                                                users#edit
#                      user GET    /users/:id(.:format)                                                                     users#show
#                           PATCH  /users/:id(.:format)                                                                     users#update
#                           PUT    /users/:id(.:format)                                                                     users#update
#                           DELETE /users/:id(.:format)                                                                     users#destroy
#             post_comments GET    /posts/:post_id/comments(.:format)                                                       comments#index
#                           POST   /posts/:post_id/comments(.:format)                                                       comments#create
#          new_post_comment GET    /posts/:post_id/comments/new(.:format)                                                   comments#new
#              edit_comment GET    /comments/:id/edit(.:format)                                                             comments#edit
#                   comment GET    /comments/:id(.:format)                                                                  comments#show
#                           PATCH  /comments/:id(.:format)                                                                  comments#update
#                           PUT    /comments/:id(.:format)                                                                  comments#update
#                           DELETE /comments/:id(.:format)                                                                  comments#destroy
#                post_likes POST   /posts/:post_id/likes(.:format)                                                          likes#create
#                      like DELETE /likes/:id(.:format)                                                                     likes#destroy
#          like_posts_posts GET    /posts/like_posts(.:format)                                                              posts#like_posts
#                     posts GET    /posts(.:format)                                                                         posts#index
#                           POST   /posts(.:format)                                                                         posts#create
#                  new_post GET    /posts/new(.:format)                                                                     posts#new
#                 edit_post GET    /posts/:id/edit(.:format)                                                                posts#edit
#                      post GET    /posts/:id(.:format)                                                                     posts#show
#                           PATCH  /posts/:id(.:format)                                                                     posts#update
#                           PUT    /posts/:id(.:format)                                                                     posts#update
#                           DELETE /posts/:id(.:format)                                                                     posts#destroy
#                     login GET    /login(.:format)                                                                         sessions#new
#                           POST   /login(.:format)                                                                         sessions#create
#                    logout DELETE /logout(.:format)                                                                        sessions#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root 'users#new'
  resources :relationships, only: [:create, :destroy]
  resources :users
  resources :posts, shallow: true do
    resources :comments
    resources :likes, only: [:create, :destroy]
    collection do
      get :like_posts
      get :search
    end
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :mypage do
    resource :account, only: [:edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :bigint           not null, primary key
#  avatar           :string(255)
#  crypted_password :string(255)
#  email            :string(255)      not null
#  name             :string(255)      not null
#  salt             :string(255)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  authenticates_with_sorcery!

  mount_uploader :avatar, AvatarUploader

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: "followed"

  scope :recent, -> (count) { order(created_at: :desc).limit(count) }

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  def own?(object)
    id == object.user_id
  end

  def like(post)
    like_posts << post
  end

  def unlike(post)
    like_posts.destroy(post)
  end

  def like?(post)
    like_posts.include?(post)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.destroy(other_user)
  end

  def follow?(other_user)
    following.include?(other_user)
  end

  def feed
    Post.where(user_id: following_ids << id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.page(params[:page]).order(created_at: :desc)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to login_path, success: 'ユーザーを作成しました'
    else
      flash.now[:danger] = 'ユーザーの作成に失敗しました'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.slim
= form_with url: relationships_path(followed_id: user.id), method: :post, remote: true do |f|
  = f.submit "フォロー", class: "btn btn-raised btn-outline-warning"

app/views/users/_follow_area.html.slim
- if logged_in? && current_user.id != user.id
  div id="follow-area-#{user.id}"
    - if current_user.follow?(user)
      = render 'users/unfollow', user: user
    - else
      = render 'users/follow', user: user

app/views/users/_unfollow.html.slim
= form_with url: relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), method: :delete, remote: true do |f|
  = f.submit "アンフォロー", class: "btn btn-raised btn-warning"

app/views/users/_user.html.slim
.user.mb-3.d-flex.justify-content-between
  = link_to user_path(user) do
    = image_tag user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
    = user.name
  = render 'users/follow_area', user: user
hr

app/views/users/index.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3.mb-3
      .card
        .card-body
          = render @users
    .col-md-6.col-12.offset-md-3
      = paginate @users

app/views/users/new.html.slim
.login-register-form
  .login-register-form-inner
    .card.mb-3
      = form_with model: @user, class: 'card-body', local: true do |f|
        = render 'shared/error_messages', object: @user
        .form-group
          = f.label :name, class: 'bmd-label-floating'
          = f.text_field :name, class: 'form-control'
        .form-group
          = f.label :email, class: 'bmd-label-floating'
          = f.email_field :email, class: 'form-control'
        .form-group
          = f.label :password, class: 'bmd-label-floating'
          = f.password_field :password, class: 'form-control'
        .form-group
          = f.label :password_confirmation, class: 'bmd-label-floating'
          = f.password_field :password_confirmation, class: 'form-control'

        = f.submit '登録', class: 'btn btn-raised btn-primary'
    .card
      .card-body
        | アカウントをお持ちですか
        = link_to 'ログインする', login_path

app/views/users/show.html.slim
.container
  .row
    .col-md-10.offset-md-1
      .card
        .card-body
          - if current_user&.id == @user.id
            .text-center.mb-3
              = link_to 'プロフィール編集', edit_mypage_account_path
          .text-center.mb-3
            = image_tag @user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
          .profile.text-center.mb-3
            = @user.name
          .text-center
            = render 'follow_area', user: @user
          hr
          .row
            = render partial: "posts/thumbnail_post", collection: @user.posts