config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                      root GET    /                                                                                        users#new
#             relationships POST   /relationships(.:format)                                                                 relationships#create
#              relationship DELETE /relationships/:id(.:format)                                                             relationships#destroy
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                 edit_user GET    /users/:id/edit(.:format)                                                                users#edit
#                      user GET    /users/:id(.:format)                                                                     users#show
#                           PATCH  /users/:id(.:format)                                                                     users#update
#                           PUT    /users/:id(.:format)                                                                     users#update
#                           DELETE /users/:id(.:format)                                                                     users#destroy
#             post_comments GET    /posts/:post_id/comments(.:format)                                                       comments#index
#                           POST   /posts/:post_id/comments(.:format)                                                       comments#create
#          new_post_comment GET    /posts/:post_id/comments/new(.:format)                                                   comments#new
#              edit_comment GET    /comments/:id/edit(.:format)                                                             comments#edit
#                   comment GET    /comments/:id(.:format)                                                                  comments#show
#                           PATCH  /comments/:id(.:format)                                                                  comments#update
#                           PUT    /comments/:id(.:format)                                                                  comments#update
#                           DELETE /comments/:id(.:format)                                                                  comments#destroy
#                post_likes POST   /posts/:post_id/likes(.:format)                                                          likes#create
#                      like DELETE /likes/:id(.:format)                                                                     likes#destroy
#          like_posts_posts GET    /posts/like_posts(.:format)                                                              posts#like_posts
#                     posts GET    /posts(.:format)                                                                         posts#index
#                           POST   /posts(.:format)                                                                         posts#create
#                  new_post GET    /posts/new(.:format)                                                                     posts#new
#                 edit_post GET    /posts/:id/edit(.:format)                                                                posts#edit
#                      post GET    /posts/:id(.:format)                                                                     posts#show
#                           PATCH  /posts/:id(.:format)                                                                     posts#update
#                           PUT    /posts/:id(.:format)                                                                     posts#update
#                           DELETE /posts/:id(.:format)                                                                     posts#destroy
#                     login GET    /login(.:format)                                                                         sessions#new
#                           POST   /login(.:format)                                                                         sessions#create
#                    logout DELETE /logout(.:format)                                                                        sessions#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root 'users#new'
  resources :relationships, only: [:create, :destroy]
  resources :users
  resources :posts, shallow: true do
    resources :comments
    resources :likes, only: [:create, :destroy]
    collection do
      get :like_posts
      get :search
    end
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :mypage do
    resource :account, only: [:edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_before_login_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'InstaClone', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    form.form-inline.my-2.my-lg-0.mr-auto
      input.form-control.mr-sm-2 placeholder="Search" type="search" /
      button.btn.btn-outline-success.my-2.my-sm-0 type="submit"  Search
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        = link_to 'ポスト一覧', '#', class: 'nav-link'
      li.nav-item
        = link_to 'ログイン', login_path, class: 'nav-link'

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_messages.alert.alert-danger 
    ul.mb-0
      - object.errors.full_messages.each do |msg|
        li= msg

app/views/shared/_flash_messages.html.slim
- flash.each do |message_type, message|
  div class=("alert alert-#{message_type}") = message

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'InstaClone', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    = render 'posts/search_form', search_form: @search_form
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        = link_to new_post_path, class: "nav-link" do
          = icon 'far', 'image', class: 'fa-lg'
      li.nav-item
        = link_to like_posts_posts_path, class: "nav-link" do
          = icon 'far', 'heart', class: 'fa-lg'
      li.nav-item
        = link_to user_path(current_user), class: "nav-link" do
          = icon 'far', 'user', class: 'fa-lg'
      li.nav-item
        = link_to 'ログアウト', logout_path, class: 'nav-link', method: :delete

app/views/shared/_modal.html.slim
#modal-container