config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                      root GET    /                                                                                        users#new
#             relationships POST   /relationships(.:format)                                                                 relationships#create
#              relationship DELETE /relationships/:id(.:format)                                                             relationships#destroy
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                 edit_user GET    /users/:id/edit(.:format)                                                                users#edit
#                      user GET    /users/:id(.:format)                                                                     users#show
#                           PATCH  /users/:id(.:format)                                                                     users#update
#                           PUT    /users/:id(.:format)                                                                     users#update
#                           DELETE /users/:id(.:format)                                                                     users#destroy
#             post_comments GET    /posts/:post_id/comments(.:format)                                                       comments#index
#                           POST   /posts/:post_id/comments(.:format)                                                       comments#create
#          new_post_comment GET    /posts/:post_id/comments/new(.:format)                                                   comments#new
#              edit_comment GET    /comments/:id/edit(.:format)                                                             comments#edit
#                   comment GET    /comments/:id(.:format)                                                                  comments#show
#                           PATCH  /comments/:id(.:format)                                                                  comments#update
#                           PUT    /comments/:id(.:format)                                                                  comments#update
#                           DELETE /comments/:id(.:format)                                                                  comments#destroy
#                post_likes POST   /posts/:post_id/likes(.:format)                                                          likes#create
#                      like DELETE /likes/:id(.:format)                                                                     likes#destroy
#          like_posts_posts GET    /posts/like_posts(.:format)                                                              posts#like_posts
#                     posts GET    /posts(.:format)                                                                         posts#index
#                           POST   /posts(.:format)                                                                         posts#create
#                  new_post GET    /posts/new(.:format)                                                                     posts#new
#                 edit_post GET    /posts/:id/edit(.:format)                                                                posts#edit
#                      post GET    /posts/:id(.:format)                                                                     posts#show
#                           PATCH  /posts/:id(.:format)                                                                     posts#update
#                           PUT    /posts/:id(.:format)                                                                     posts#update
#                           DELETE /posts/:id(.:format)                                                                     posts#destroy
#                     login GET    /login(.:format)                                                                         sessions#new
#                           POST   /login(.:format)                                                                         sessions#create
#                    logout DELETE /logout(.:format)                                                                        sessions#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root 'users#new'
  resources :relationships, only: [:create, :destroy]
  resources :users
  resources :posts, shallow: true do
    resources :comments
    resources :likes, only: [:create, :destroy]
    collection do
      get :like_posts
      get :search
    end
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :mypage do
    resource :account, only: [:edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  body       :text(65535)      not null
#  images     :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  mount_uploaders :images, PostImageUploader
  serialize :images, JSON
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :body, presence: true, length: { maximum: 1000}
  validates :images, presence: true

  # wordをに部分一致するpostsに絞り込み
  scope :body_contain, -> (word) { where('posts.body LIKE ?', "%#{word}%") }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: %i[new create edit update destroy]

  def index
    @posts = if current_user
                current_user.feed.includes(:user).page(params[:page]).order(created_at: :desc)
              # feedを使わずに取得する場合
              #  my_post = current_user.posts
              #  following_user_posts = []
              #  current_user.following.each do |user|
              #    following_user_posts.push(user.posts)
              #  end
              #  my_post + following_user_posts
             else
               Post.all.includes(:user).page(params[:page]).order(created_at: :desc)
             end

    @users = User.recent(5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, notice: "投稿成功"
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    @comment = Comment.new
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path, notice: "投稿を編集しました"
    else
      render :new
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to posts_path
  end

  def like_posts
    @posts = current_user.like_posts.includes(:user).order(created_at: :desc).page(params[:page]).per(10)
    render :index
  end

  def search
    # form_withのscopeでsearchを指定することで、searchがパラメーターの頭につく
    @search_form = SearchPostsForm.new(params.require(:search).permit(:body))
    @posts = @search_form.search.includes(:user).page(params[:page])
  end

  private
    def post_params
      params.require(:post).permit(:body, images: [])
    end
end

app/views/posts/_form.html.slim
= form_with model: post, local: true do |f|
  = render partial: "shared/error_messages", locals: { object: post }
  .form-group 
    = f.label :images
    = f.file_field :images, multiple: true, class: "form-control"
    - post.images.each do |image|
      = image_tag image.url, size: '100*100', class: "image-thumbnail"
  .form-group 
    = f.label :body
    = f.text_area :body, class: "form-control"
  = f.submit class: "btn btn-raised btn-primary"

app/views/posts/_like.html.slim
= link_to post_likes_path(post), method: :post, remote: true do
  = icon 'far', 'heart', class: "fa-lg"

app/views/posts/_like_area.html.slim
div id="like_area-#{post.id}"
  - if current_user.like?(post)
    = render 'unlike', post: post
  -else
    = render 'like', post: post

app/views/posts/_like_posts.html.slim
.container
  .row
    .col-md-8.col-12
      = render @posts
      = pagintae @posts
    .col-md-4.col-12
      - if logged_in?
        .profile-box.mb-3
          = image_tag 'profile-placeholder.png', size: '50*50', class: 'rounded-circle mr-1'
          = current_user.name
      .user-box
        .card
          .card-header
            | ユーザー　
          .card-body
            .user.mb-3
              = image_tag 'profile-placeholder.png', size: '40*40', class: 'rounded-cidle mr-1'
              | ダミー京介
            .user.mb-3
              = image_tag 'profile-placeholder.png', size: '40*40', class: 'rounded-cidle mr-1'
              | ダミー布袋
            .user.mb-3
              = image_tag 'profile-placeholder.png', size: '40*40', class: 'rounded-cidle mr-1'
              | ダミー時松
            .user.mb-3
              = image_tag 'profile-placeholder.png', size: '40*40', class: 'rounded-cidle mr-1'
              | ダミー真
          .card-footer
            = link_to "全て見る", "#"

app/views/posts/_post.html.slim
.card-mb-5.post
  .card-header
    .d-flex.align-items-center
      = link_to user_path(post.user) do
        = image_tag post.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
        = post.user.name
      - if current_user&.own?(post)
        = link_to post_path(post), class: 'mr-3', method: :delete, data: { confirm: "本当に削除しますか?" } do
          = icon 'far', 'trash-alt', class: "fa-lg"
        = link_to edit_post_path(post) do
          = icon 'far', 'edit', class: "fa-lg"
      - if logged_in? && !current_user.own?(post)
        .ml-auto
          = render 'like_area', post: post
  = link_to post_path(post) do
    .swiper-container
      .swiper-wrapper
        - post.images.each do |image|
          .swiper-slide
            = image_tag image.url, class: 'card-img-top'
      .swiper-pagination
  .card-body
    .card-text
      = post.body

app/views/posts/_search_form.html.slim
= form_with model: search_form, url: search_posts_path, scope: :search, class: "form-inline my-2 my-lg-0 mr-auto", method: :get, local: true do |f|
  = f.search_field :body, class: "form-control mr-sm-2", placeholder: "本文"
  = f.submit "Search", class: "btn btn-outline-success my-2 my-sm-0"

app/views/posts/_thumbnail_post.html.slim
.col-md-4.mb-3
  = link_to post_path(thumbnail_post), class: "thumbs" do
    = image_tag thumbnail_post.images.first.url

app/views/posts/_unlike.html.slim
= link_to like_path(current_user.likes.find_by(post_id: post.id)), method: :delete, remote: true do
  = icon 'fa', 'heart', class: 'fa-lg'

app/views/posts/edit.html.slim
.container
  .row
    .col-md-6.col-12.offset-3
      .card
        .card-body
          = render partial: 'form', locals: { post: @post }

app/views/posts/index.html.slim
.container
  .row
    .col-md-8.col-12
      - if @posts.present?
        = render @posts
      - else
        .text-center.font-weight-bold
          | 投稿がありません
      = paginate @posts
    .col-md-4.col-12
      - if logged_in?
        .profile-box.mb-3
          = image_tag current_user.avatar.url, size: "50*50", class: 'rounded-circle mr-1'
          = link_to current_user.name, edit_mypage_account_path
      .user-box
        .card
          .card-header
            | ユーザー
          .card-body
            = render User.recent(5)
          .card-footer
            = link_to "すべて見る", users_path

app/views/posts/new.html.slim
.container 
  .row 
    .col-md-6.col-12.offset-md-3 
      .card 
        .card-body 
          = render partial: 'form', locals: { post: @post }

app/views/posts/search.html.slim
.container
  .row
    .col-md-8.col-12.offset-md-2
      h2.text-center
        | 検索結果: #{@posts.total_count}件
      = render @posts
      = paginate @posts

app/views/posts/show.html.slim
.post-detail.card
  .image-box
    .swiper-container
      .swiper-wrapper
        - @post.images.each do |image|
          .swiper-slide
            = image_tag image.url
      .swiper-pagination
  .image-info-box
    .profile-box.p-3
      .d-flex.align-items-center
        = image_tag @post.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
        = @post.user.name
        - if current_user&.own?(@post)
          .ml-auto
            = link_to post_path(@post), class: 'mr-3', method: :delete, data: {confirm: '本当に削除しますか？'} do
              = icon 'far', 'trash-alt', class: 'fa-lg'
            = link_to edit_post_path(@post) do
              = icon 'far', 'edit', class: 'fa-lg'
    hr.m-0
    .post-body.p-3
      .row.no-gutters
        .col-2
          = image_tag @post.user.avatar.url, size: '40x40', class: 'rounded-circle'
        .col-10
          = simple_format(@post.body)
      hr
      = render 'comments/comments', comments: @comments
    hr.m-0
    .post-comment.p-3
      = render 'comments/form', post: @post, comment: @comment